version: '3'

services:
  occ1:
    image: occ:latest
    volumes:
      - /home/rok/Documents/urdf_rospackages/src:/ros_ws/src
      - /home/rok/Documents/urdf_creator:/scripts_occ
    #command: stdbuf -o L /bin/bash
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
